---
server:
  port: ${SERVER_PORT:9780}

---
spring:
  kafka:
    streams:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29091}
      application-id: ${APPLICATION_ID:data_validator}
      replication-factor: ${REPLICATION_FACTOR:1}